### PR TITLE
Support for Debian 8

### PR DESCRIPTION
**Pull request by dpattmann**
Hi,

I added some lines of code to support Debian 8 and I updated the image versions in the .kitchen.yml file.

I also replaced the up2date with the apt cookbook and removed Debian 6 (Squeeze) from test-kitchen. 

Best,
Dennis

### CODE REVIEW

**Comment by TheSerapher** [comment]
👋  @dpattmann :D

Removing up2date and adding APT should break any CentOS distribution? Unless upstream APT has changed to ignore any Non-Debian based distribution.

I will have to fix the `metadata.rb` too in order to be Chef 12 compliant again.

**Comment by dpattmann** [comment]
Hi @TheSerapher, version 3 of the apt cookbook has fixed this issue. :wink: 

I will update my commit to set a version >= 3 in the Berksfile.

**Comment by TheSerapher** [comment]
Dont think you need to ... It's only used in Kitchen anyway. Just making sure new pulls don't run into converge issues.

**Comment by TheSerapher** [comment]
Thank you! :-)

**Comment by dpattmann** [comment]
You're welcome! :-)

**Pull request merged**
