### PR TITLE
Pull Request : Add SSL support

### PR DESCRIPTION
**Pull request by Gazzonyx**
I ended up not actually needing this, but someone else might want it, so I'm throwing this code over the wall.  One thing to note is that this adds a dependency on the openssl cookbook.  Not sure if that's a deal-breaker or not.

### CODE REVIEW

**Comment by TheSerapher** [comment]
Quick question:

* Should it be enabled by default?
* Only self-signed supported?

Good idea though, maybe we can expand the support to full certificates :-)

**Comment by TheSerapher** [comment]
And check the build errors and fix as required :-)

**Comment by Gazzonyx** [comment]
So, funny story.  I needed an SFTP server setup and for whatever reason it didn't occur to me, until right after I added the signed cert, that I was building an FTPS server. :)

I'll add full-ish support for SSL, fix those build errors and send a new pull request later today or tomorrow.  Do you have a preference if I close this PR and open a new one or just commit over this open one?

**Comment by TheSerapher** [comment]
Feel free to update this one :-)

**Comment by Gazzonyx** [comment]
Just a heads up, this is still on my radar but I've got a fire to put out at work, so it'll probably get done during the weekend.

**Comment by Gazzonyx** [comment]
I've still got to write some integration tests, but how does commit https://github.com/Gazzonyx/chef-vsftpd/commit/906dc73d524d76bf2b7a99d94f7b576599c68541 strike your fancy?

**Comment by TheSerapher** [comment]
That looks pretty good!

**Comment by TheSerapher** [comment]
Completely forgot about this, so sorry.

**Pull request merged**
